### ISSUE TITLE
Copilot and tabs

### ISSUE THREAD

**Issue by filipejunqueira** [radleylewis/nvim#9]
Hi man, I'm sorry for creating an issue here. I'm well aware this is your personal neovim config and that this is probably very experimental. I've followed your YT video and got my own config running. 

I am however having an issue with accepting the copilot's line suggestion. It autocompletes fine, but I can't accept it (if that makes sense?) The normal "Tab" press key won't do the job. Nor would ENTER. Under copilots.lua I have the same accept = "<CR>", as you. So I think my copilot is correctly authenticated. The .config/github-copilot/hosts.json seems to exist and it has my user and oauth_token ok 👍🏻.

In a desperation move to try to find out what the issue was, I moved my entire .config/nvim/lua folder to lua.bak and cloned your entire repo so I could run exactly your configuration. Running your exact config (including with the .json files) still gets me the same annoying behavior with copilot.  Please note that I'm a noob when it comes to nvim and lazy and all that stuff. My Lazy input is as follows. I'm not sure either if I should be loading copilot.lua on every instance of neovim. 

![image](https://github.com/radleylewis/nvim/assets/22006279/59454242-e8b6-4df1-8626-8d2227338e8f)

Finally thank you for the amazing content. I don't think there is such a complete guide (from scratch) as the one you have.

**Comment by radleylewis** [comment]
@filipejunqueira sorry I missed this! For copilot with my config if you want to accept the current line suggestion I have it mapped to `alt` + `L`.

You can see this under the `suggestion` field in the `copilot.lua` file. (NOTE: it is confusing as `M` is `Alt`):

```lua
suggestion = {
  enabled = true,
  auto_trigger = true,
  debounce = 75,
  keymap = {
	  accept = "<M-l>", -- this line accepts the current suggestion
	  accept_word = false,
	  accept_line = false,
	  next = "<M-]>",
	  prev = "<M-[>",
	  dismiss = "<C-]>",
  },
},
```

I hope this helps!
